[package]
name = "iron-gcd"
version = "0.1.0"
authors = ["pleeplop <pleeplop@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hello = { path = "../hello" }
iron = "0.5.1"
mime = "0.2.3"
router = "0.5.1"
urlencoded = "0.5.0"
